###########################################################################################
## NOTE: Costmap conversion is experimental. Its purpose is to combine many point        ##
## obstales into clusters, computed in a separate thread in order to improve the overall ## 
## efficiency of local planning. However, the implemented conversion algorithms are in a ##
## very early stage of development. Contributions are welcome!                           ##
###########################################################################################

TebLocalPlannerROS:

  ## Costmap converter plugin   
  #costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
  costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSRANSAC"
  #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSMCCH"
  #costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSConcaveHull"
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5
 
 
  ## Configure plugins (namespace move_base/costmap_to_lines or move_base/costmap_to_polygons)
  ## costmap_converter/CostmapToLinesDBSRANSAC, costmap_converter/CostmapToLinesDBSMCCH, costmap_converter/CostmapToPolygonsDBSMCCH
  costmap_converter/CostmapToLinesDBSRANSAC:
    cluster_max_distance: 0.4  # Maximum distance between points in a cluster for line extraction using DBSCAN algorithm.
    cluster_min_pts: 2  # Minimum number of points required to form a cluster for line extraction using DBSCAN algorithm.
    ransac_inlier_distance: 0.15  # Maximum distance threshold for a point to be considered an inlier in RANSAC line fitting.
    ransac_min_inliers: 10  # Minimum number of inliers required to accept a RANSAC line fit.
    ransac_no_iterations: 1500  # Number of iterations to perform in the RANSAC line fitting algorithm.
    ransac_remainig_outliers: 3  # Maximum number of remaining outliers allowed after RANSAC line fitting.
    ransac_convert_outlier_pts: True  # Flag indicating whether to convert the outlier points to obstacles.
    ransac_filter_remaining_outlier_pts: False  # Flag indicating whether to filter out the remaining outlier points.
    convex_hull_min_pt_separation: 0.1  # Minimum distance between points on the convex hull to avoid overlapping.
