scan_filter_chain:
- name: angle
  type: laser_filters/LaserScanAngularBoundsFilter
  params:
    lower_angle: -2.25  # The lower bound for the angle in radians.
    upper_angle: 2.25  # The upper bound for the angle in radians.

