DashgoDriver:
  ros__parameters:    
    port: /dev/ttyUSB0
    baudrate: 115200
    timeout: 0.1
    rate: 50
    sensorstate_rate: 10

    # === Robot Module activation
    use_smotheer: True  # To use the smoother nodelet set use_smoother to True
    useSonar: False
    useImu: True
    use_base_controller: True
    base_controller_rate: 10

    # For a robot that uses base_footprint, change base_frame to base_footprint
    base_frame: base_footprint

    
    # === Robot drivetrain parameters
    wheel_diameter: 0.1280
    wheel_track: 0.341
    encoder_resolution: 1200
    gear_reduction: 1.0
    motors_reversed: False

    accel_limit: 1.0

    #Activate modes
    pub_encoders: False
    voltage_pub: False
    show_statics: False
    

    #Sonar parameters
    sonar_height: 0.115

    sonar0_offset_yaw: 0.524
    sonar0_offset_x: 0.18
    sonar0_offset_y: 0.10

    sonar1_offset_yaw: 0.0
    sonar1_offset_x: 0.20
    sonar1_offset_y: 0.0

    sonar2_offset_yaw: -0.524
    sonar2_offset_x: 0.18
    sonar2_offset_y: -0.10

    sonar3_offset_yaw: 3.14
    sonar3_offset_x: -0.20
    sonar3_offset_y: 0.0