local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  ransform_tolerance: 0.2

  update_frequency: 5.0
  publish_frequency: 2.0

  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05

  plugins:
  - name: obstacle_laser_layer
    type: 'costmap_2d::ObstacleLayer'

  obstacle_laser_layer:
    enabled: true
    observation_sources: laser_scan_sensor
    combination_method: 1

    laser_scan_sensor:
      sensor_frame: base_scan
      data_type: LaserScan
      topic: /scan_filtered
      expected_update_rate: 0.3
      observation_persistence: 1.0
      inf_is_valid: true
      marking: true
      clearing: true
      raytrace_range: 3.0
      obstacle_range: 2.5
      min_obstacle_height: -0.1
      max_obstacle_height: 0.3

  inflation_layer:
    enabled            : true
    inflation_radius   : 0.3
    cost_scaling_factor: 2.0